### ISSUE TITLE
beaglebone black/green

### ISSUE THREAD

**Issue by robots** [jks-prv/5370_proc#1]
Hello,

I would like to build this project (I know i am late to the party), and in the documentation you are mentioning BB-green, and then it disappears from documentation.

What is the reason BBG does not work with this project? As far as i understand its the same schematic with HDMI transmitter removed or am I wrong?

You mention that image is built on KiwiSDR image, and kiwisdr works with bbg.

Thanks

**Comment by jks-prv** [comment]
Apologies for the delay in replying.

You know, I can't remember why the software doesn't work on BBG. I have this dim memory that the Debian 7 for BBG is not quite the same as Debian 7 for BBB, but I could be wrong about that. I never updated the 5370 code to use the GPIO handling in Debian 8 as for example with the KiwiSDR code (which supports Debian 7, 8, 9 and 10).

**Comment by SteveDallas** [comment]
If I recall correctly, BBG shipped with Debian 8 and there were driver issues that prevented the BBB version of Debian 7 from running on the BBG, but it’s been five years or so since I tried to do anything with it.

**Comment by jks-prv** [comment]
Yeah, that sounds more like it.

**Comment by robots** [comment]
Hi,
thanks for reply :) I ended up using BBB with debian (very new at that time), and i struggled few hours with the PRU, but managed to get it to work correctly.
