### ISSUE TITLE
Are there any rev 3 PCBs for sale anywhere?

### ISSUE THREAD

**Issue by marclefevre** [jks-prv/5370_proc#2]
I'm interested in building one of these and thought I'd try to find PCB that's already been fab'd before I ordered 5 for myself. I'm just looking for a bare board.

**Comment by jks-prv** [comment]
The only possibility I know of is this old email exchange (2019) I had with someone who was going to have some PCBs built and then sell the extras. I don't know if any of that actually occurred. But it's probably worth asking him.

John

----
Hi Yves,

Thank you for asking.

Yes, please do as you wish. The material is open source. So you may replicate and sell boards, even for a profit.

And thank you for doing this. I’m not sure how much demand there will be. But perhaps some people will be happy it is available again.

Best regards,
John

On Nov 8, 2019, at 8:11 AM, [zfefm@gmx.de](mailto:zfefm@gmx.de) wrote:

Hi,

as you stated you will make no more HP 5370 processor replacement
boards, and you kindly provided everything  needed to make them, I let
fabricate some bare PCB.

I have more PCBs then I need myself and thought to offer them, more or
less, for what I have paid for them (perhaps at eevblog and the time-nut
mailing list).
Preparing that, I realized that I can find nowhere in the documentation
any note about if this is OK.
Thus I thought I should ask you if this is OK from your side. Is it?

Best regards
and thank you for all the efforts you have put in that project,
Yves

**Comment by marclefevre** [comment]
I was able to obtain a PCB.

**Comment by jks-prv** [comment]
Okay, glad you were able to do this.
